# Generated by Django 4.2.9 on 2026-03-04 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('live', 'Live Camera')], max_length=10)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='detections/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame_number', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.FloatField(blank=True, help_text='Timestamp dalam detik', null=True)),
                ('detections', models.JSONField(default=list, help_text='Array of detected objects')),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='annotated/%Y/%m/%d/')),
                ('total_persons', models.IntegerField(default=0)),
                ('persons_with_helmet', models.IntegerField(default=0)),
                ('persons_with_vest', models.IntegerField(default=0)),
                ('persons_without_helmet', models.IntegerField(default=0)),
                ('persons_without_vest', models.IntegerField(default=0)),
                ('compliance_score', models.FloatField(default=0.0, help_text='Skor compliance 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='detection.detectionsession')),
            ],
            options={
                'ordering': ['frame_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='detection.detectionresult')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='detection.detectionsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='detectionsession',
            index=models.Index(fields=['-created_at'], name='detection_d_created_221d07_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionsession',
            index=models.Index(fields=['user', '-created_at'], name='detection_d_user_id_b8372c_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['session', 'frame_number'], name='detection_d_session_0c4a92_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['session', '-created_at'], name='detection_d_session_496be9_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['-created_at'], name='detection_a_created_9e73b2_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['session', '-created_at'], name='detection_a_session_8b30e7_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_acknowledged'], name='detection_a_is_ackn_b68cad_idx'),
        ),
    ]
